version: "3"
services:
  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/potatozation-of-mars
      PORT: 5000
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - .:/app/
    depends_on:
      - postgres
      - pgadmin

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: potatozation-of-mars

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  db-data:
  pgadmin-data:
