version: "3"
services:
  web:
    build:
      context: .
    env_file:
      - ./.env.dev
    ports:
      - "${PORT}:${PORT}"
      - "8080:8080" # webpack serves files through this port
    volumes:
      - .:/app/
      - /app/node_modules/bcrypt/ # https://stackoverflow.com/a/61221812
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
