FROM node:14.16.1-alpine AS build
WORKDIR /build
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

FROM node:14.16.1
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production
COPY --from=build /build/dist ./dist
COPY . .
EXPOSE 3000
CMD ["node", "./index.js"]
