version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-potatozation-of-mars}
    ports:
      - "5432:5432"
    restart: always
