version: "3"
services:
  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/potatozation-of-mars
      PORT: 5000
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - .:/app/

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: potatozation-of-mars
