version: "3"
services:
  web:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-potatozation-of-mars}
      PORT: 5000
    ports:
      - "5000:5000"
      - "8080:8080" # webpack serves files through this port
    volumes:
      - .:/app/
      - /app/node_modules/bcrypt/ # https://stackoverflow.com/a/61221812
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-potatozation-of-mars}
