export const FETCH_ENJOYER_SETTINGS_REQUEST = 'FETCH_ENJOYER_SETTINGS_REQUEST'
export const FETCH_ENJOYER_SETTINGS_SUCCESS = 'FETCH_ENJOYER_SETTINGS_SUCCESS'
export const FETCH_ENJOYER_SETTINGS_FAILURE = 'FETCH_ENJOYER_SETTINGS_FAILURE'
