export const FETCH_TOPICS_LIST_REQUEST = 'FETCH_TOPICS_LIST_REQUEST'
export const FETCH_TOPICS_LIST_SUCCESS = 'FETCH_TOPICS_LIST_SUCCESS'
export const FETCH_TOPICS_LIST_FAILURE = 'FETCH_TOPICS_LIST_FAILURE'
