export * from './AuthTemplate'
export * from './Error404Template'
export * from './Error500Template'
export * from './ForumTemplate'
export * from './GameTemplate'
export * from './LiderboardTemplate'
export * from './ProfileTemplate'
export * from './SignUpTemplate'
