export { default as Auth } from './Auth'
export { default as Error404 } from './Error404'
export { default as Forum } from './Forum'
export { default as Game } from './Game'
export { default as Liderboard } from './Liderboard'
export { default as Profile } from './Profile'
export { default as SignUp } from './SignUp'
