export const FETCH_LEADERBOARD_REQUEST = 'FETCH_LEADERBOARD_REQUEST'
export const FETCH_LEADERBOARD_SUCCESS = 'FETCH_LEADERBOARD_SUCCESS'
export const FETCH_LEADERBOARD_FAILURE = 'FETCH_LEADERBOARD_FAILURE'
