export const FETCH_USER_SETTINGS_REQUEST = 'FETCH_USER_SETTINGS_REQUEST'
export const FETCH_USER_SETTINGS_SUCCESS = 'FETCH_USER_SETTINGS_SUCCESS'
export const FETCH_USER_SETTINGS_FAILURE = 'FETCH_USER_SETTINGS_FAILURE'
