export * from './user/userRouterFactory'
export * from './topic/topicRouterFactory'
export * from './comment/commentRouterFactory'
export * from './reaction/reactionRouterFactory'
export * from './theme/themeRouterFactory'
export * from './userSettings/userSettingsFactory'
