export const UPDATE_IUSER_PASSWORD_REQUEST = 'UPDATE_IUSER_PASSWORD_REQUEST'
export const UPDATE_IUSER_PASSWORD_SUCCESS = 'UPDATE_IUSER_PASSWORD_SUCCESS'
export const UPDATE_IUSER_PASSWORD_FAILURE = 'UPDATE_IUSER_PASSWORD_FAILURE'
