export const UPDATE_LEADERBOARD_REQUEST = 'UPDATE_LEADERBOARD_REQUEST'
export const UPDATE_LEADERBOARD_SUCCESS = 'UPDATE_LEADERBOARD_SUCCESS'
export const UPDATE_LEADERBOARD_FAILURE = 'UPDATE_LEADERBOARD_FAILURE'
