export const CREATE_USER_SETTINGS_REQUEST = 'CREATE_USER_SETTINGS_REQUEST'
export const CREATE_USER_SETTINGS_SUCCESS = 'CREATE_USER_SETTINGS_SUCCESS'
export const CREATE_USER_SETTINGS_FAILURE = 'CREATE_USER_SETTINGS_FAILURE'
