name: Deploy

on:
  push:
    branches:
      - task_89

jobs:
  deploy:
    name: Deploy to Yandex Cloud VM
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Test
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          - run: yarn install
          - run: yarn test

      - name: Login to Yandex Cloud Container Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.OAUTH_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.production
          push: true
          tags: cr.yandex/crp44cptgt36thhl5qjc/dublin-potatozation-of-mars
