name: Deploy

on:
  push:
    branches:
      - task_89

jobs:
  unit-tests:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn test

  deploy:
    name: Deploy to Yandex Cloud VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: docker login --username oauth --password ${{ secrets.OAUTH_TOKEN }} cr.yandex

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.production
          push: true
          tags: cr.yandex/crp44cptgt36thhl5qjc/dublin-potatozation-of-mars
