name: Project tests

on: [push, pull_request]

jobs:
  unit-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.15.4-alpine'
    - run: yarn install
    - run: yarn test
